package BIPlugIn;

public class Gui extends Framework.Gui {
    /** Creates new form calcGui */
    public Gui(String name) {
        super(name);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void initComponents() {
        calc = new Calc();
        Result.setText("0");
        pack();
    }

    javax.swing.JTextField Result;
    
    public void display() {
        Framework.Gui cg = this;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cg.setVisible(true);
            }
        });
    }
}
